### PR TITLE
HDS-1518: clear SearchInput suggestions on submit.

### PR DESCRIPTION
**Pull request by NikoHelle**
## Description

From Slack: 

I'm using <SearchInput> and facing an issue with search suggestions. Those suggestions won't disappear when running the search by Enter key nor clicking the magnifier icon in search input field.

## Related Issue

https://helsinkisolutionoffice.atlassian.net/browse/HDS-1518

## How Has This Been Tested?

Added tests that fail without these changes.

[HDS-1518]: https://helsinkisolutionoffice.atlassian.net/browse/HDS-1518?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by NikoHelle** [comment]
Suggestions won't close (on Chrome) if you just write "Day" and hit enter. Do not select anything.

**Comment by minevala** [comment]
It now seems to reopen the suggestions once more if I select something with a mouse (maybe it does not cancel the search anymore etc.):

https://user-images.githubusercontent.com/1610860/210571822-ef59b232-8d3e-410f-8c9b-716764dde31a.mov

**Comment by minevala** [comment]
It would be nice to have live demo in the hds-demos so it would be faster to review

**Comment by NikoHelle** [comment]
Demo added:

https://city-of-helsinki.github.io/hds-demo/hds-1518-search-input/?path=/story/components-searchinput--with-suggestions-spinner

Good that storybook has the asyc demo, it revealed other hiccups when hitting enter/click/reset/search before previous search was over.

**Review by minevala — APPROVED** [review]
I think it works now much better and I also started to understand the functionality through code changes. Nice fix all around 🏅

**Pull request merged**
