### PR TITLE
Release-4.0.0: (HDS-2348) Add first PlayWright tests for Core components

### PR DESCRIPTION
**Pull request by mrTuomoK**
## Description

Adds 1st test for core components too (new Button and new Tag). Moved & renamed previous React tests under /react/react-* and also prefixed the screenshots accordingly.

## Related Issue

Closes [HDS-2348](https://helsinkisolutionoffice.atlassian.net/browse/HDS-2348)

## Motivation and Context

Previously we did not have any tests for Core components

## How Has This Been Tested?

- running locally in Docker -> 1st clean and build all -> build core-storybook and react-storybook -> goto ./e2e/docker -> run run.sh script (needs docker to be installed)

## Demos:

Links to demos are in the comments

## Add to changelog

- Not needed, the testing & creating instructions will be done at some point later on.

[HDS-2348]: https://helsinkisolutionoffice.atlassian.net/browse/HDS-2348?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by Riippi** [comment]
I did't get this to run without errors locally. Probably because I am missing some step before running the test or doing something in wrong order or something? I did build core / react / storybooks. I could use a "how to run hds playwright tests locally" guide.
The actual code looks fine to me.

**Comment by mrTuomoK** [comment]
> I did't get this to run without errors locally. Probably because I am missing some step before running the test or doing something in wrong order or something? I did build core / react / storybooks. I could use a "how to run hds playwright tests locally" guide.
> 
> The actual code looks fine to me.

It's because the local test have to be run with the Docker command since locally running it on MacOs or Windows gives wrong results.

**Comment by Riippi** [comment]
> > I did't get this to run without errors locally. Probably because I am missing some step before running the test or doing something in wrong order or something? I did build core / react / storybooks. I could use a "how to run hds playwright tests locally" guide.
> > The actual code looks fine to me.
> 
> It's because the local test have to be run with the Docker command since locally running it on MacOs or Windows gives wrong results. I'll make instructions after my holidays :D
> 
> Now back from holidays, updated the "How Has This Been Tested?"-part to include the instructions how to test locally, can you now test @Riippi ? The testing documentation will be updated in another ticket.

yes, got it running now.

**Review by Riippi — APPROVED** [review]
👍

**Pull request closed without merging**
