### PR TITLE
Feature/tabs new docs

### PR DESCRIPTION
**Pull request by minevala**
## Description
- Split buttons.mdx into smaller page sections
- Use tabs to combine page sections on index page 

Depends on: #627 

## Related Issue
- https://helsinkisolutionoffice.atlassian.net/browse/HDS-915

## Motivation and Context
- By using Tabs the page size stays smaller and does not feel that overwhelming for the user.

## How Has This Been Tested?
- Locally on dev machine

## Screenshots (if appropriate):
Screenshot 2022-01-18 at 17 44 11

[👉 Storybook Demo](https://city-of-helsinki.github.io/hds-demo/docsite-playground/elements/components/buttons/)

### CODE REVIEW

**Review by ronijaakkola — APPROVED** [review]

**Comment by VilleMiekkoja** [comment]
Not sure if related to this PR, but the Acccessibility tab seems to contain more guidance than just a11y? I wonder if there would be a better name for it to cover all what it contains 🤔

**Comment by VilleMiekkoja** [comment]
Would be possible/worth it to set height of Tabs always according to its most highest TabPanel? With the current implementation the content of the page jumps/scrolls when tab is switched due to different heights:

￼

**Comment by minevala** [comment]
> Would it be possible/worth it to set height of Tabs always according to its most highest TabPanel? With the current implementation the content of the page jumps/scrolls when tab is switched due to different heights:
> 
>  1ECA45CE-B94D-4BBF-9086-AAE35DEF6D21.mov

It feels that it should be fixed in Tabs component 🤔

**Comment by minevala** [comment]
> Not sure if related to this PR, but the Acccessibility tab seems to contain more guidance than just a11y? I wonder if there would be a better name for it to cover all what it contains 🤔

The content is more of placeholder things. I copied it from current documentation

**Pull request merged**
