### PR TITLE
Hds 1978 mobile menu animation

### PR DESCRIPTION
**Pull request by harriplappalainen**
## Description

Header's mobile menu is missing animations on open and close. It should be the same as language selector dropdown has.
**Bonus:** Fixed Breadcrumb and Container stories using Header.

## Related Issue

https://helsinkisolutionoffice.atlassian.net/browse/HDS-1978

## How Has This Been Tested?
Localhost
[Demo](https://city-of-helsinki.github.io/hds-demo/hds-1978-mobile-menu-animation/?path=/story/components-header--with-full-features)

### CODE REVIEW

**Comment by NikoHelle** [comment]
There is something weird in the Loki images. In some cases, a part of the mobile menu logo is seen above the header? Some images also have +2px height for some invisible reason. The reason should be investigated, because height of the header is quite important in our css.

**Comment by mrTuomoK** [comment]
There's also this height & fitting issue still that when opening the menu the scrollbar appears and the disappears when the menu is again stationary. Can be seen in this video (very narrow scrollbar on mobile emulator, wider in desktop browser). Don't know if it's related to this ticket or not but still.

https://github.com/City-of-Helsinki/helsinki-design-system/assets/8654955/993b6d60-1aae-409b-b8e0-6ee5aab1c21b

**Comment by harriplappalainen** [comment]
> There is something weird in the Loki images. In some cases, a part of the mobile menu logo is seen above the header? 

Fixed! Needed to fiddle around with Breadcrumb, Container, Hero and Login stories and setting storybook conf `layout: 'fullscreen'`helped as well which caused a lot of "changed" reference images.

> Some images also have +2px height for some invisible reason. The reason should be investigated, because height of the header is quite important in our css.

Now there is only two ref imgs with 2px more height, the minimal headers. I don't understand the reason for it. The height of component hasn't changed, it's the same as in production but the ref img height has changed for some reason 🤔

**Comment by harriplappalainen** [comment]
> There's also this height & fitting issue still that when opening the menu the scrollbar appears and the disappears when the menu is again stationary. Can be seen in this video (very narrow scrollbar on mobile emulator, wider in desktop browser). Don't know if it's related to this ticket or not but still. In some circumstances will make the content slightly jump.

I didn't notice the content jumping. [There's a ticket](https://helsinkisolutionoffice.atlassian.net/browse/HDS-1977) about scrollbar making action bar jump but I didn't see that either. I did notice that the submenus are rendered and are vertically scrollable in mobile views, I disabled that in commit [bc6e921](https://github.com/City-of-Helsinki/helsinki-design-system/pull/1176/commits/bc6e9212ef49aeaaae590c9694ad5080062e1a38).

**Comment by NikoHelle** [comment]
This is probably the reason why so many loki images changed: `layout: 'fullscreen`?

**Comment by mrTuomoK** [comment]
Is this just in Storybook or?

https://github.com/City-of-Helsinki/helsinki-design-system/assets/8654955/c92d2030-dd56-4394-bf63-12747de907cf

**Review by NikoHelle — APPROVED** [review]
Nice smooth animation! 👍

**Review by mrTuomoK — APPROVED** [review]
Fine by be too, good job 👍 (and sorry for testing an old version 1st 🤦 😆  )

**Pull request merged**
