### PR TITLE
Feature 447 Token for focus color

### PR DESCRIPTION
**Pull request by timwessman**
## Description

Created `color-focus-outline` -token for focus color. Modified all focusable core components to use it

## Related Issue

[https://helsinkisolutionoffice.atlassian.net/browse/HDS-447](https://helsinkisolutionoffice.atlassian.net/browse/HDS-447)

Closes #

## Motivation and Context

This makes a change of focus color possible.

## How Has This Been Tested?

All focus colors should look the same as before. 

To test if the new token works, you can try to change the focus color of all focusable components just by changing the color value in `/design-tokens/tokens/color/ui/focus.json`.  Build project and go to see your color change in Storybook

### CODE REVIEW

**Comment by mrTuomoK** [comment]
Is it truly that they are the same color for both focus and background? Well in the ticket it says: "Create separate **tokens** for focus colour (background and border) and change components to use them." 🤷 Dunno 🤷

**Comment by timwessman** [comment]
I didn't understand `background` -part. Focus don't normally change the background of components (only outline or border), and I didn't find that kind of behavior from HDS either.

**Comment by mrTuomoK** [comment]
Yeah I don't know, maybe we'll need to ask the HDS-people too.

**Comment by laurakarhu** [comment]
That background thing was a weird blurb, I don't know how it got there :D I removed it from the issue as well, so you can forget that part.

**Review by mrTuomoK — APPROVED** [review]
Seems legit

**Pull request merged**
