### PR TITLE
(HDS-2057) add ErrorSummary to docs

### PR DESCRIPTION
**Pull request by mrTuomoK**
Add ErrorSummary component to doc site.

## Description

Self explanatory :)

## Related Issue

[HDS-2057](https://helsinkisolutionoffice.atlassian.net/browse/HDS-2057)

## How Has This Been Tested?

- local tests with updated reference images & snapshot

## Add to changelog
- [x] Added needed line to changelog 

[HDS-2057]: https://helsinkisolutionoffice.atlassian.net/browse/HDS-2057?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by NikoHelle — APPROVED** [review]
Excellent!

**Comment by Riippi** [comment]
Should this have it's own card in here?
Screenshot 2024-01-05 at 10 24 33

**Comment by mrTuomoK** [comment]
> Should this have it's own card in here? Screenshot 2024-01-05 at 10 24 33

Ah true... need to make, good spotting.

**Comment by mrTuomoK** [comment]
Hey who makes the image(s) for this? ping @SillanmakiA perhaps?

**Comment by SillanmakiA** [comment]
> Hey who makes the image(s) for this? ping @SillanmakiA perhaps? for ErrorSummary component, pull this branch `HDS-2057-error-summary-documentation` clean & build -> and go to /site and start it.

I added the image in my commit. Are you @mrTuomoK able to continue from there?

**Comment by mrTuomoK** [comment]
I'm still to add the images... hung up with other stuff still...

**Review by Riippi — APPROVED** [review]
nice

**Pull request merged**
