### PR TITLE
[Feature] Add minSize property for FileInput React component

### PR DESCRIPTION
**Pull request by umeetiusbaar**
## Description

Add `minSize` property for FileInput React component in addition to the current `maxSize` property. Use size 0 as default which accepts empty files as the component has been doing for now. Some applications (e.g. Haitaton) requires that attachment files have some non-zero length content.

## Related Issue
https://github.com/City-of-Helsinki/helsinki-design-system/issues/1293

## Motivation and Context
Our application [Haitaton](https://github.com/City-of-Helsinki/haitaton-ui) requires that uploaded attachment files have non-zero length content.

## How Has This Been Tested?
Added a Jest test similar to `maxSize` test.

## Screenshots (if appropriate):
image

## Add to changelog
- Added a line in [CHANGELOG.md](CHANGELOG.md)

### CODE REVIEW

**Review by mrTuomoK — CHANGES_REQUESTED** [review]
All looks good, please add to CHANGELOG if you will 👍 thank you :) ping @umeetiusbaar

**Comment by umeetiusbaar** [comment]
> All looks good, please add to CHANGELOG if you will 👍 thank you :) ping @umeetiusbaar

Thank you! Added a line in CHANGELOG.md.

**Comment by mrTuomoK** [comment]
Hmm... I just wonder if the minSize should be in KB too (like the maxSize) and not B?

**Review by mrTuomoK — APPROVED** [review]
All good by me, thx 👍

**Review by NikoHelle — APPROVED** [review]
Excellent work!

**Pull request merged**
