### PR TITLE
HDS-1387: refocus cookie consent title on language change

### PR DESCRIPTION
**Pull request by NikoHelle**
## Description

When user changes the language, focus is lost and the modal shrinks.

Fixed by adding the modal title as a dependency to the useEffect which handles the initial focusing.

If user selects the same language again, the focus is moved back to the language selector button for better accessibility.

## How Has This Been Tested?

Added tests for both scenarios: language is changed and same language is reselected.

👉 [Demo](https://city-of-helsinki.github.io/hds-demo/cookie-consent/?path=/story/components-cookieconsent--english-modal-version)

### CODE REVIEW

**Comment by VilleMiekkoja** [comment]
Could you add a demo of this?

**Comment by NikoHelle** [comment]
> 

What kind of demo? Do you mean a story?

**Comment by VilleMiekkoja** [comment]
I think it's a bit weird that it works differently depending on which language is selected. I mean the difference in selecting current language or a new language. But it works ok and we can go with this 👍

**Review by VilleMiekkoja — APPROVED** [review]
Nice clean fix! 🕺

**Pull request merged**
