### PR TITLE
Feature/input info text

### PR DESCRIPTION
**Pull request by minevala**
## Description
- Add support for info text in various inputs

## Closes 
- https://helsinkisolutionoffice.atlassian.net/browse/HDS-955

## Related Issue
- https://helsinkisolutionoffice.atlassian.net/browse/HDS-901

## Motivation and Context
- Purpose of the input's info text is to tell the user that the value has been updated with an alternative input method: Clear button, drag-and-drop area, etc.
- This is needed in the new FileInput component

## How Has This Been Tested?
- Manually on dev's machine
- In loki tests

## Screenshots (if appropriate):
Näyttökuva 2021-8-26 kello 13 22 01
Näyttökuva 2021-8-26 kello 13 22 22
Näyttökuva 2021-8-26 kello 13 21 47

### CODE REVIEW

**Review by VilleMiekkoja — APPROVED** [review]
Well done 🏅

**Review by VilleMiekkoja — APPROVED** [review]
Nice 👍

**Review by laurakarhu — APPROVED** [review]
Nice job!

**Comment by ronijaakkola** [comment]
Added documentation for the info text element.

**Review by laurakarhu — APPROVED** [review]
Good job, thanks!

**Pull request merged**
