### PR TITLE
Feature/status label icon

### PR DESCRIPTION
**Pull request by minevala**
## Description
- Add icon support for status-label. StatusLabel component has a new iconLeft property.

## Closes
- https://helsinkisolutionoffice.atlassian.net/browse/HDS-584

## How Has This Been Tested?
- Locally on dev's machine
- Loki tests in the PR CI pipeline

## Screenshots (if appropriate):
Näyttökuva 2021-4-21 kello 10 49 21

Näyttökuva 2021-4-21 kello 10 49 55

Näyttökuva 2021-4-21 kello 10 49 41

👉 [Storybook demo](https://city-of-helsinki.github.io/hds-demo/status-label/?path=/story/components-status-label--icons)

### CODE REVIEW

**Review by VilleMiekkoja — APPROVED** [review]
👍  Good job!

**Review by laurakarhu — APPROVED** [review]
Yay :)

**Comment by ronijaakkola** [comment]
Was the Tag height matched with the StatusLabel height yet?

**Comment by minevala** [comment]
> Was the Tag height matched with the StatusLabel height yet?

No, it is not as simple to change:
- needs refactoring (CSS duplication)
- needs more component tests since it is also part of Combobox and Select components

**Pull request merged**
