### PR TITLE
HDS-1968: fix extra p tags on docs site

### PR DESCRIPTION
**Pull request by NikoHelle**
## Description

Whenever there is new line in a .mdx file, a `<p>` is added there.

There is no way to prevent that, so ended up filtering out useless p-tags in our components on the docs site.

Added a helper function to check, if component's child is a `<p>` and if it is, its children are hoisted and the `<p>` is stripped.

Another solution would have been a Gatsby plugin, but that would have been a lot more complex. Also targeting places where a `<p>` would have been needed and where not, would required a lot more work as a plugin processes all contents on the page.

Now only the components that clearly should not have p-tags are checked.

Because almost all pages use the Tabs-component, the list of changed files is a long one.

Closes [HDS-1968](https://helsinkisolutionoffice.atlassian.net/browse/HDS-1968)

## How Has This Been Tested?

Locally browsing through built docs.

[Demo](https://city-of-helsinki.github.io/hds-demo/hds-1968-p-tags)

## Add to changelog
No additions to changelog. Contents or components not changed.

[HDS-1968]: https://helsinkisolutionoffice.atlassian.net/browse/HDS-1968?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by harriplappalainen — COMMENTED** [review]
That'll do 🐷 I think this is good enough. I don't think a Gatsby plugin would ever work as intended in all places. Also good work on generally cleaning up little things in the mdx-files 🎉 

I found out that StatusLabel should be switched from hds-react to custom component in the following places:
- site/src/docs/about/accessibility/hds-accessibility.mdx
- site/src/docs/components/date-input/tabs.mdx
- site/src/docs/components/dialog/tabs.mdx
- site/src/docs/components/login/tabs.mdx

And maybe it should be changed in other pages too? 
- site/src/docs/foundation/guidelines/inclusivity.mdx
- site/src/docs/patterns/cookies/basics.mdx
- site/src/docs/patterns/cookies/common-helsinki-cookies.mdx
- site/src/docs/patterns/cookies/using-the-cookieconsent.mdx
- site/src/docs/patterns/navigation/building-navigation.mdx (here it's using the rounded variant, that's deprecated)
- site/src/docs/patterns/navigation/examples.mdx (also rounded variant)

Other than that I think this is good.

**Comment by NikoHelle** [comment]
All should be changed now. Rounded Statuslabel was used in other places, so removed those too.

**Comment by NikoHelle** [comment]
Demo is up to date.

**Review by harriplappalainen — APPROVED** [review]
All good! 🚀

**Review by mrTuomoK — APPROVED** [review]
All good :)

**Pull request merged**
