### PR TITLE
HDS-1775 Remove rectangular StatusLabel

### PR DESCRIPTION
**Pull request by harriplappalainen**
## Description

Remove rectangular StatusLabel, rounded is the new default. Update reference images and documentation accordingly.

## Related Issue

https://helsinkisolutionoffice.atlassian.net/browse/HDS-1775

## How Has This Been Tested?
Localhost, tests

[React storybook](https://city-of-helsinki.github.io/hds-demo/rect-statuslabel-react/?path=/story/components-statuslabel--icons)
[Core storybook](https://city-of-helsinki.github.io/hds-demo/rect-statuslabel-core/?path=/story/components-statuslabel--icons)
[Doc](https://city-of-helsinki.github.io/hds-demo/rect-statuslabel-doc/)

### CODE REVIEW

**Comment by harriplappalainen** [comment]
**Notice!** The huge amount of loki ref changes is caused by [Icon library build PR](https://github.com/City-of-Helsinki/helsinki-design-system/pull/1063) icon changes. It was first targeted for `development` but then changed to `release-3.0.0`, and perhaps the loki tests weren't updated. I'm not sure why the PR tests didn't fail though. [Here's the action](https://github.com/City-of-Helsinki/helsinki-design-system/actions/runs/5586961022) when tests were run during merging.

**Comment by mrTuomoK** [comment]
> I'm not sure why the PR tests didn't fail though.

The images look identical thus not failing maybe 🤷‍♂️

**Comment by mrTuomoK** [comment]
ping @harriplappalainen small conflict to fix 😉, I'll re-check this after the fix.

**Comment by mrTuomoK** [comment]
Were we supposed to completely remove the rectangle StatusLabel or just make the rounded one the default? @harriplappalainen 🤷

**Comment by harriplappalainen** [comment]
> Were we supposed to completely remove the rectangle StatusLabel or just make the rounded one the default? @harriplappalainen 🤷 The ticket says something like that but were we? 🤔 😄

We were supposed to remove the rectangular version.

**Comment by mrTuomoK** [comment]
Ok goooood then 👌🏻

**Review by mrTuomoK — APPROVED** [review]
Good to go! niiice 😸

**Pull request merged**
