### PR TITLE
(HDS-2157) Tag mark deprecated and changed properties

### PR DESCRIPTION
**Pull request by mrTuomoK**
## Description

Tag mark deprecated and changed properties in the next major release.

## Related Issue

[HDS-2157](https://helsinkisolutionoffice.atlassian.net/browse/HDS-2157)

## How Has This Been Tested?

- local machine

## Add to changelog
- [x] Added needed line to changelog

[HDS-2157]: https://helsinkisolutionoffice.atlassian.net/browse/HDS-2157?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by NikoHelle** [comment]
The Navigation component was deprecated with

```
/**
 * Navigation will be removed in the next major release. Upcoming Header component will be the replacement.
 * @deprecated
 */
export const Navigation = ({
```

This might be enough?

https://jsdoc.app/tags-deprecated

**Comment by mrTuomoK** [comment]
Hmm... didn't we agree not to deprecate the whole component? 🤔

**Comment by NikoHelle** [comment]
Ah, true. Just replacing with new one.

**Comment by NikoHelle** [comment]
But shouldn't we still mark the props deprecated?

https://dev.to/dgreene1/how-to-properly-deprecate-3027

Adding plain text to the props won't propably be seen anywhere unless devs actually follow type links or hover over a prop.

**Comment by mrTuomoK** [comment]
Ok let's see... I though I just copied the way Riippi did earlier :D

**Comment by mrTuomoK** [comment]
Now it should be properly done @NikoHelle . @deprecated all which's use will completely be changed or completely removed, so didn't deprecate for example `id` since default value is the only thing that will change.

**Review by laurakarhu — APPROVED** [review]
Making space for new shiny tag!

**Pull request merged**
