### PR TITLE
HDS-1945 Fix input buttons focus

### PR DESCRIPTION
**Pull request by harriplappalainen**
## Description

None the buttons inside React input components can be focused. This was caused by using a wrong variable name. Core has no issues.

Affected components that underwent changes in this PR:
- CookieConsent
- Dropdown
- FileInput
- NumberInput
- SearchInput
- TextInput
- (internal) SelectedItems

## Related Issue

https://helsinkisolutionoffice.atlassian.net/browse/HDS-1945

## How Has This Been Tested?
Localhost
[Storybook demo](https://city-of-helsinki.github.io/hds-demo/fix-input-button-focus/)

To do
- [x] Fix cookie consent accordion show/hide button focus

### CODE REVIEW

**Review by laurakarhu — APPROVED** [review]
Good catch, thanks! And I'm glad there was a common easy way to fix problem.

**Review by mrTuomoK — APPROVED** [review]
Good easy fix :) btw if we are really really strict to use british-english everywhere, our `color` should be `colour` (Dunno if I nagged about this way back :D )

**Comment by harriplappalainen** [comment]
> Good easy fix :) btw if we are really really strict to use british-english everywhere, our color should be colour (Dunno if I nagged about this way back :D )

I noticed this horrible disparity with this PR as well, that the doc site has `colour` but design tokens have `color` 😁 There was some discussion about this before. Probably users don't notice this though.

**Comment by mrTuomoK** [comment]
These carets (or what are they called?), can't be focused anywhere in CookieConsent at least 
image

**Review by mrTuomoK — APPROVED** [review]
Couldn't spot any more bugs 👍

**Pull request merged**
